
export const provinces = [
  { label: "Buenos Aires", value: "buenos_aires" },
  { label: "Ciudad Autónoma de Buenos Aires", value: "caba" },
  { label: "Catamarca", value: "catamarca" },
  { label: "Chaco", value: "chaco" },
  { label: "Chubut", value: "chubut" },
  { label: "Córdoba", value: "cordoba" },
  { label: "Corrientes", value: "corrientes" },
  { label: "Entre Ríos", value: "entre_rios" },
  { label: "Formosa", value: "formosa" },
  { label: "Jujuy", value: "jujuy" },
  { label: "La Pampa", value: "la_pampa" },
  { label: "La Rioja", value: "la_rioja" },
  { label: "Mendoza", value: "mendoza" },
  { label: "Misiones", value: "misiones" },
  { label: "Neuquén", value: "neuquen" },
  { label: "Río Negro", value: "rio_negro" },
  { label: "Salta", value: "salta" },
  { label: "San Juan", value: "san_juan" },
  { label: "San Luis", value: "san_luis" },
  { label: "Santa Cruz", value: "santa_cruz" },
  { label: "Santa Fe", value: "santa_fe" },
  { label: "Santiago del Estero", value: "santiago_del_estero" },
  { label: "Tierra del Fuego", value: "tierra_del_fuego" },
  { label: "Tucumán", value: "tucuman" }
];