export const study_options = [
  {
    "label": "Prestaciones Biología Molecular",
    "value": "prestaciones_biologia_molecular",
    "items": [
      { "label": "G-LIFE 27", "value": "g_life_27" },
      { "label": "BRCA 1/2 Somático con panel HRR", "value": "brca_1_2_somatico_con_panel_hrr" },
      { "label": "G-LIFE 52", "value": "g_life_52" },
      { "label": "G-LIFE 500", "value": "g_life_500" },
      { "label": "G-LIFE 500 + HRD", "value": "g_life_500_hrd" },
      { "label": "G-LIFE LIQUID", "value": "g_life_liquid" },
      { "label": "G-LIFE ENDO", "value": "g_life_endo" },
      { "label": "EGFR", "value": "egfr" },
      { "label": "KRAS", "value": "kras" },
      { "label": "BRAF", "value": "braf" },
      { "label": "NRAS", "value": "nras" },
      { "label": "POLE", "value": "pole" },
      { "label": "MSI", "value": "msi" },
      { "label": "G-ESSENCE MAMA", "value": "g_essence_mama" },
      { "label": "G-ESSENCE GINECO-MAMA", "value": "g_essence_gineco_mama" },
      { "label": "G-ESSENCE COLON", "value": "g_essence_colon" },
      { "label": "G-ESSENCE PRÓSTATA", "value": "g_essence_prostata" },
      { "label": "G-ESSENCE MELANOMA", "value": "g_essence_melanoma" },
      { "label": "G-ESSENCE Astra Zeneca-específico", "value": "g_essence_astra_zeneca" },
      { "label": "G-ESSENCE BRCA1/2 (Germinal)", "value": "g_essence_brca1_2_germinal" },
      { "label": "G-ESSENCE 30", "value": "g_essence_30" },
      { "label": "G-ESSENCE 50", "value": "g_essence_50" },
      { "label": "G-ESSENCE 100", "value": "g_essence_100" },
      { "label": "G-ESSENCE FAST", "value": "g_essence_fast" },
      { "label": "G-ESSENCE PLUS", "value": "g_essence_plus" },
      { "label": "Variante familiar", "value": "variante_familiar" },
      { "label": "EXOMA COMPLETO", "value": "exoma_completo" },
      { "label": "EXOMA CLÍNICO", "value": "exoma_clinico" },
      { "label": "PANEL CARDIO ETC", "value": "panel_cardio_etc" },
      { "label": "PANEL CARDIO A", "value": "panel_cardio_a" },
      { "label": "PANEL CARDIO M", "value": "panel_cardio_m" },
      { "label": "PANEL CARDIO D", "value": "panel_cardio_d" },
      { "label": "PANEL CARDIO HAP", "value": "panel_cardio_hap" },
      { "label": "PANEL CARDIO AC", "value": "panel_cardio_ac" },
      { "label": "PANEL NEURO", "value": "panel_neuro" },
      { "label": "PROSIGNA", "value": "prosigna" }
    ]
  },
  {
    "label": "Prestaciones Anatomía Patológica",
    "value": "prestaciones_anatomia_patologica",
    "items": [
      { "label": "Oncologia General / Primario desconocido", "value": "oncologia_general_primario_desconocido" },
      { "label": "Hematopatología Diagnóstica Integral", "value": "hematopatologia_diagnostica_integral" },
      { "label": "Nefropatología Diagnóstica Integral", "value": "nefropatologia_diagnostica_integral" },
      { "label": "Neuropatología Diagnóstica Integral", "value": "neuropatologia_diagnostica_integral" },
      { "label": "Dermatopatología Diagnóstica Integral", "value": "dermatopatologia_diagnostica_integral" },
      { "label": "Clasificación Molecular de Carcinoma Endometrial", "value": "clasificacion_molecular_carcinoma_endometrial" },
      { "label": "Panel Mama - IHQ test (RE RP HER2 Ki67)", "value": "panel_mama_ihq_test" },
      { "label": "Panel MMR Inestabilidad de microsatélites (MLH-1, PMS2, MSH2 y MSH6)", "value": "panel_mmr_inestabilidad_microsatelites" },
      { "label": "Panel Receptores de Estrógenos / Progesterona", "value": "panel_receptores_estrogenos_progesterona" },
      { "label": "HER2 (clon 4B5) IHQ test", "value": "her2_clon_4b5_ihq_test" },
      { "label": "PDL1 (clon SP263)", "value": "pdl1_clon_sp263" },
      { "label": "ROS1 - IHQ test", "value": "ros1_ihq_test" },
      { "label": "ALK (clon D5F3-Pulmón) - IHQ test", "value": "alk_clon_d5f3_pulmon_ihq_test" },
      { "label": "BRAF V600E - IHQ test", "value": "braf_v600e_ihq_test" },
      { "label": "Tinciones Especiales x1", "value": "tinciones_especiales_x1" },
      { "label": "HER2 Amplification FISH test", "value": "her2_amplification_fish_test" },
      { "label": "ROS1 BA FISH test", "value": "ros1_ba_fish_test" },
      { "label": "MET amplificación FISH test", "value": "met_amplificacion_fish_test" },
      { "label": "ALK BA FISH test", "value": "alk_ba_fish_test" },
      { "label": "MYC BA FISH test", "value": "myc_ba_fish_test" },
      { "label": "BCL2 BA FISH test", "value": "bcl2_ba_fish_test" },
      { "label": "IGH BA FISH test", "value": "igh_ba_fish_test" }
    ]
  }
]